# Generated by Django 5.0.1 on 2024-01-05 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elevator',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('current_floor', models.IntegerField(default=0)),
                ('user_requests', models.JSONField(default=list)),
                ('operational', models.BooleanField(default=True)),
                ('direction', models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('stop', 'Stop')], default='stop', max_length=10)),
                ('door_status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='closed', max_length=10)),
            ],
        ),
    ]
