# Generated by Django 5.0.1 on 2024-01-05 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevator_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='elevator',
            name='current_floor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elevators', to='elevator_app.floor'),
        ),
        migrations.CreateModel(
            name='FloorRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elevators_count', models.IntegerField(default=1)),
                ('user_requests', models.JSONField(default=list)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floor_requests', to='elevator_app.floor')),
            ],
        ),
    ]
