# Generated by Django 5.0.1 on 2024-01-05 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevator_app', '0002_floor_alter_elevator_current_floor_floorrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elevator',
            name='current_floor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elevators', to='elevator_app.floor'),
        ),
    ]
