# Generated by Django 5.0.1 on 2024-01-05 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevator_app', '0003_alter_elevator_current_floor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elevator',
            name='current_floor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='elevator_app.floor'),
            preserve_default=False,
        ),
    ]
